export interface SuburbImportConfig {
  slug: string;
  suburb: string;
  councilExternalId: string;
  councilName: string;
  center: { latitude: number; longitude: number };
  streets: string[];
  baysPerStreet: number;
}

export const SUBURB_IMPORTS: Record<string, SuburbImportConfig> = {
  "ascot-vale": {
    slug: "ascot-vale",
    suburb: "Ascot Vale",
    councilExternalId: "city-of-moonee-valley",
    councilName: "City of Moonee Valley",
    center: { latitude: -37.7792, longitude: 144.9215 },
    baysPerStreet: 10,
    streets: [
      "Ascot Vale Road",
      "Union Road",
      "Maribyrnong Road",
      "Farnsworth Avenue",
      "Chapman Street",
      "Kent Street",
      "McPherson Street",
      "Glass Street",
      "The Grove",
      "Masala Street",
      "Bank Street",
      "Beatrice Street",
      "Caddy Street",
      "Dutton Street",
      "Ethel Street",
      "Francis Street",
      "Gloucester Street",
      "Langs Road",
      "Margaret Street",
      "Melbourne Avenue",
      "New Street",
      "Ordnung Street",
      "Parker Street",
      "Rosser Street",
      "Smith Street",
      "St Leonards Avenue",
      "Turner Street",
      "Victory Boulevard",
      "Wells Street",
      "Wingrove Street",
      "Afton Street",
      "Brunswick Road",
      "Canterbury Road",
      "Fletcher Street",
      "Gordon Street",
      "Hawke Street",
      "Keilor Road",
      "Moonee Ponds Central",
    ],
  },
  altona: {
    slug: "altona",
    suburb: "Altona",
    councilExternalId: "city-of-hobsons-bay",
    councilName: "Hobsons Bay City Council",
    center: { latitude: -37.8697, longitude: 144.8298 },
    baysPerStreet: 10,
    streets: [
      "Pier Street",
      "Railway Street",
      "Millers Road",
      "Queen Street",
      "Blyth Street",
      "Grieve Parade",
      "Civic Parade",
      "Maidstone Street",
      "Sargood Street",
      "Upton Street",
      "Victoria Street",
      "Harrington Square",
      "Lock Avenue",
      "McArthurs Road",
      "Seaholme Place",
      "Benton Street",
      "Cherry Lake Road",
      "Esplanade",
      "Freemans Road",
      "Gordon Street",
      "Hannah Street",
      "Kororoit Creek Road",
      "Lynch Street",
      "Mount Street",
      "Nelson Street",
      "Parver Avenue",
      "Queen Street Altona",
      "Rose Street",
      "Saffron Street",
      "Tamarisk Grove",
      "Wells Street Altona",
      "Zammit Street",
    ],
  },
};
